-- Add missing SPR1 territorial and administrative columns
ALTER TABLE spr1_records
ADD COLUMN IF NOT EXISTS lures VARCHAR(6),
ADD COLUMN IF NOT EXISTS regresu VARCHAR(3),
ADD COLUMN IF NOT EXISTS uslresu VARCHAR(3),
ADD COLUMN IF NOT EXISTS cittu VARCHAR(3),
ADD COLUMN IF NOT EXISTS statciv VARCHAR(1),
ADD COLUMN IF NOT EXISTS titstud VARCHAR(1),
ADD COLUMN IF NOT EXISTS condprof VARCHAR(1),
ADD COLUMN IF NOT EXISTS soggrich VARCHAR(2),
ADD COLUMN IF NOT EXISTS icd9cm VARCHAR(10),
ADD COLUMN IF NOT EXISTS icd9cm_c VARCHAR(10),
ADD COLUMN IF NOT EXISTS proroghe VARCHAR(1),
ADD COLUMN IF NOT EXISTS durata_prev VARCHAR(5),
ADD COLUMN IF NOT EXISTS data_val DATE,
ADD COLUMN IF NOT EXISTS quoric VARCHAR(10),
ADD COLUMN IF NOT EXISTS imptick VARCHAR(10);